name: pi_pcas
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.2.1
  firebase_auth: ^3.4.2
  provider: ^6.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/icon1.png
    - lib/assets/images/icon2.png
    - lib/assets/images/icon3.png
    - lib/assets/images/icon4.png
    - lib/assets/images/icon5.png
    - lib/assets/images/icon6.png
    - lib/assets/images/icon7.png
    - lib/assets/images/icon8.png
    - lib/assets/images/icon9.png
    - lib/assets/images/icon10.png
    - lib/assets/images/icon11.png
    - lib/assets/images/icon12.png
    - lib/assets/images/icon13.png
    - lib/assets/images/icon14.png
    - lib/assets/images/icon15.png
    - lib/assets/images/icon16.png
    - lib/assets/images/icon17.png
    - lib/assets/images/icon18.png
    - lib/assets/images/icon19.png
    - lib/assets/images/icon20.png
    - lib/assets/images/icon21.png
    - lib/assets/images/icon22.png
    - lib/assets/images/icon23.png
    - lib/assets/images/icon24.png
    - lib/assets/images/icon25.png
    - lib/assets/images/icon26.png
    - lib/assets/images/icon27.png
    - lib/assets/images/icon28.png
    - lib/assets/images/icon29.png
    - lib/assets/images/icon30.png
    - lib/assets/images/null_icon.png

    - lib/assets/images/alone_share.png
    - lib/assets/images/friends_share.png
    - lib/assets/images/so_share.png
    - lib/assets/images/coworkers_share.png
    - lib/assets/images/family_share.png

    - lib/assets/images/anxious_emotion.png
    - lib/assets/images/happy_emotion.png
    - lib/assets/images/mad_emotion.png
    - lib/assets/images/sad_emotion.png
    - lib/assets/images/satisfied_emotion.png
    - lib/assets/images/shame_emotion.png
    - lib/assets/images/motivated_emotion.png
    - lib/assets/images/alone_emotion.png
    - lib/assets/images/proud_emotion.png
    - lib/assets/images/guilt_emotion.png

    - lib/assets/images/mindfulness_module.png
    - lib/assets/images/emotional_module.png
    - lib/assets/images/suffering_module.png

    - lib/assets/images/contents/Picture1.jpg
    - lib/assets/images/contents/Picture2.jpg
    - lib/assets/images/contents/Picture3.jpg


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mulish
      fonts:
        - asset: lib/assets/fonts/Mulish-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
